### PR TITLE
Generate Typescript Typings via JsDoc 

### PR DESCRIPTION
**Pull request by samparsky**
* Adds typings to the js-libp2p-secio module
* Add typings generation to travis.yml
* Include typings test

### CODE REVIEW

**Comment by peter-donovan** [comment]
I could write them out manually and then distribute it via DefinitelyTyped if you like. I would be more than happy to help. I would imagine it shouldn't cause any issues and all of the types seem to be pretty straight forward; I've worked with crypto libraries like nacl and libsodium as well as node-forge and the native Node and Browser Crypto APIs.

**Comment by vasco-santos** [comment]
FYI: We have some typescript support decision updates on [libp2p/js-libp2p#659](https://github.com/libp2p/js-libp2p/issues/659).

**Comment by Stebalien** [comment]
(closing due to package deprecation)

**Comment by Stebalien** [comment]
(closing due to package deprecation)

**Pull request closed without merging**
