### PR TITLE
fix: cascading connection from encrypted connection to parent connection

### PR DESCRIPTION
**Pull request by pgte**
Should unblock https://github.com/libp2p/js-libp2p-switch/pull/243

### CODE REVIEW

**Comment by pgte** [comment]
Tests are timing out, but they were before this PR. Any clue on that?

**Comment by diasdavid** [comment]
@pgte locally as well? Seems that only one of the CI runs red. Perhaps increase the timeout to see what is the real reason?

**Comment by pgte** [comment]
@diasdavid locally it runs fine, and there is no test that's particularly long..
1__bash

**Comment by pgte** [comment]
@diasdavid looks like everything is green again... 🤔

**Pull request merged**
